services:
  casdoor:
    image: casbin/casdoor:latest
    container_name: xyyx-casdoor
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=release
    volumes:
      - ./conf:/conf
      - ./logs:/logs
